/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author justi
 */
import javax.swing.*;
import java.awt.event.*;
import java.util.Random;


public class SemesterProject extends javax.swing.JFrame {

    private String word;
    private int wordLength;
    private int lettersRemaining;
    private int score;
    /**
     * Creates new form SemesterProject
     */
    public SemesterProject() {
        initComponents();
        ActionListener actionListener = new ActionListener() {
            public void actionPerformed (ActionEvent event) {
                mainPanel.removeAll();
                mainPanel.add(menuPanel);
                mainPanel.repaint();
                mainPanel.revalidate();
            }
        };
        Timer timer = new Timer(100, actionListener);
        timer.setRepeats(false);
        timer.setInitialDelay(3000);
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        startPanel = new javax.swing.JPanel();
        projectLabel = new javax.swing.JLabel();
        groupLabel = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        menuLabel = new javax.swing.JLabel();
        gameButton = new javax.swing.JButton();
        scoreButton = new javax.swing.JButton();
        creditsButton = new javax.swing.JButton();
        gamePanel = new javax.swing.JPanel();
        gameLabel = new javax.swing.JLabel();
        gameBackButton = new javax.swing.JButton();
        gameSkipButton = new javax.swing.JButton();
        aButton = new javax.swing.JButton();
        bButton = new javax.swing.JButton();
        cButton = new javax.swing.JButton();
        dButton = new javax.swing.JButton();
        eButton = new javax.swing.JButton();
        fButton = new javax.swing.JButton();
        gButton = new javax.swing.JButton();
        hButton = new javax.swing.JButton();
        iButton = new javax.swing.JButton();
        jButton = new javax.swing.JButton();
        kButton = new javax.swing.JButton();
        lButton = new javax.swing.JButton();
        mButton = new javax.swing.JButton();
        nButton = new javax.swing.JButton();
        oButton = new javax.swing.JButton();
        pButton = new javax.swing.JButton();
        qButton = new javax.swing.JButton();
        rButton = new javax.swing.JButton();
        sButton = new javax.swing.JButton();
        tButton = new javax.swing.JButton();
        uButton = new javax.swing.JButton();
        vButton = new javax.swing.JButton();
        wButton = new javax.swing.JButton();
        xButton = new javax.swing.JButton();
        yButton = new javax.swing.JButton();
        zButton = new javax.swing.JButton();
        gameScoreLabel = new javax.swing.JLabel();
        letter1Label = new javax.swing.JLabel();
        letter2Label = new javax.swing.JLabel();
        letter3Label = new javax.swing.JLabel();
        letter4Label = new javax.swing.JLabel();
        letter5Label = new javax.swing.JLabel();
        letter6Label = new javax.swing.JLabel();
        letter7Label = new javax.swing.JLabel();
        letter8Label = new javax.swing.JLabel();
        answerLabel = new javax.swing.JLabel();
        niceLabel = new javax.swing.JLabel();
        tryAgainLabel = new javax.swing.JLabel();
        scorePanel = new javax.swing.JPanel();
        scoreLabel = new javax.swing.JLabel();
        scoreBackButton = new javax.swing.JButton();
        creditsPanel = new javax.swing.JPanel();
        creditsLabel = new javax.swing.JLabel();
        creditsBackButton = new javax.swing.JButton();
        gameOverPanel = new javax.swing.JPanel();
        gameOverLabel = new javax.swing.JLabel();
        gameOverEndButton = new javax.swing.JButton();
        finalScoreLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 400));

        mainPanel.setLayout(new java.awt.CardLayout());

        startPanel.setBackground(new java.awt.Color(0, 0, 0));
        startPanel.setPreferredSize(new java.awt.Dimension(600, 400));

        projectLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        projectLabel.setForeground(new java.awt.Color(255, 255, 255));
        projectLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        projectLabel.setText("CS 2450 Semester Project Ver. 1.0");
        projectLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        groupLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        groupLabel.setForeground(new java.awt.Color(255, 255, 255));
        groupLabel.setText("By: To The Moon Studios");

        javax.swing.GroupLayout startPanelLayout = new javax.swing.GroupLayout(startPanel);
        startPanel.setLayout(startPanelLayout);
        startPanelLayout.setHorizontalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(groupLabel))
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(projectLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        startPanelLayout.setVerticalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(projectLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(groupLabel)
                .addGap(63, 63, 63))
        );

        mainPanel.add(startPanel, "startPanel");

        menuPanel.setPreferredSize(new java.awt.Dimension(600, 400));

        menuLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        menuLabel.setText("Menu");

        gameButton.setText("Play");
        gameButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gameButtonMousePressed(evt);
            }
        });

        scoreButton.setText("Highscores");
        scoreButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                scoreButtonMousePressed(evt);
            }
        });

        creditsButton.setText("Credits");
        creditsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                creditsButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(menuLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                        .addComponent(gameButton)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                        .addComponent(scoreButton)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                        .addComponent(creditsButton)
                        .addGap(62, 62, 62))))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(menuLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gameButton)
                .addGap(18, 18, 18)
                .addComponent(scoreButton)
                .addGap(18, 18, 18)
                .addComponent(creditsButton)
                .addGap(41, 41, 41))
        );

        mainPanel.add(menuPanel, "menuPanel");

        gamePanel.setPreferredSize(new java.awt.Dimension(600, 400));

        gameLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        gameLabel.setText("Hang Man");

        gameBackButton.setText("Back");
        gameBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameBackButtonMouseClicked(evt);
            }
        });

        gameSkipButton.setText("Skip");
        gameSkipButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameSkipButtonMouseClicked(evt);
            }
        });

        aButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        aButton.setText("A");
        aButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aButtonMouseClicked(evt);
            }
        });

        bButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        bButton.setText("B");
        bButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bButtonMouseClicked(evt);
            }
        });

        cButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        cButton.setText("C");
        cButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cButtonMouseClicked(evt);
            }
        });

        dButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        dButton.setText("D");
        dButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dButtonMouseClicked(evt);
            }
        });

        eButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        eButton.setText("E");
        eButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eButtonMouseClicked(evt);
            }
        });

        fButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        fButton.setText("F");
        fButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fButtonMouseClicked(evt);
            }
        });

        gButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        gButton.setText("G");
        gButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gButtonMouseClicked(evt);
            }
        });

        hButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        hButton.setText("H");
        hButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hButtonMouseClicked(evt);
            }
        });

        iButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        iButton.setText("I");
        iButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iButtonMouseClicked(evt);
            }
        });

        jButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jButton.setText("J");
        jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMouseClicked(evt);
            }
        });

        kButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        kButton.setText("K");
        kButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButtonMouseClicked(evt);
            }
        });

        lButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lButton.setText("L");
        lButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lButtonMouseClicked(evt);
            }
        });

        mButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        mButton.setText("M");
        mButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mButtonMouseClicked(evt);
            }
        });

        nButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        nButton.setText("N");
        nButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nButtonMouseClicked(evt);
            }
        });

        oButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        oButton.setText("O");
        oButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oButtonMouseClicked(evt);
            }
        });

        pButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        pButton.setText("P");
        pButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pButtonMouseClicked(evt);
            }
        });

        qButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        qButton.setText("Q");
        qButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qButtonMouseClicked(evt);
            }
        });

        rButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        rButton.setText("R");
        rButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rButtonMouseClicked(evt);
            }
        });

        sButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        sButton.setText("S");
        sButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sButtonMouseClicked(evt);
            }
        });

        tButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        tButton.setText("T");
        tButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tButtonMouseClicked(evt);
            }
        });

        uButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        uButton.setText("U");
        uButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uButtonMouseClicked(evt);
            }
        });

        vButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        vButton.setText("V");
        vButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vButtonMouseClicked(evt);
            }
        });

        wButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        wButton.setText("W");
        wButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wButtonMouseClicked(evt);
            }
        });

        xButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        xButton.setText("X");
        xButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xButtonMouseClicked(evt);
            }
        });

        yButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        yButton.setText("Y");
        yButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yButtonMouseClicked(evt);
            }
        });

        zButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        zButton.setText("Z");
        zButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zButtonMouseClicked(evt);
            }
        });

        gameScoreLabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        gameScoreLabel.setText("Score: 100");

        letter1Label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        letter1Label.setText(" ___");

        letter2Label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        letter2Label.setText("___");

        letter3Label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        letter3Label.setText("___");

        letter4Label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        letter4Label.setText("___");

        letter5Label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        letter5Label.setText("___");

        letter6Label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        letter6Label.setText("___");

        letter7Label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        letter7Label.setText("___");

        letter8Label.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        letter8Label.setText("___");

        answerLabel.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        answerLabel.setText("ANSWER:");

        niceLabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        niceLabel.setForeground(new java.awt.Color(0, 204, 51));
        niceLabel.setText("Nice!");

        tryAgainLabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        tryAgainLabel.setForeground(new java.awt.Color(255, 51, 51));
        tryAgainLabel.setText("Try Again!");

        javax.swing.GroupLayout gamePanelLayout = new javax.swing.GroupLayout(gamePanel);
        gamePanel.setLayout(gamePanelLayout);
        gamePanelLayout.setHorizontalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanelLayout.createSequentialGroup()
                .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gamePanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(oButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(qButton)
                        .addGap(21, 21, 21))
                    .addGroup(gamePanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gamePanelLayout.createSequentialGroup()
                                .addComponent(rButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(uButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(vButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(wButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(xButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(yButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(zButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gamePanelLayout.createSequentialGroup()
                                .addComponent(aButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(gamePanelLayout.createSequentialGroup()
                                        .addComponent(answerLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(letter1Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(letter2Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(letter3Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(letter4Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(letter5Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(letter6Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(letter7Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(letter8Label))
                                    .addGroup(gamePanelLayout.createSequentialGroup()
                                        .addComponent(bButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(eButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(gButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(hButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(iButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(gamePanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gamePanelLayout.createSequentialGroup()
                        .addComponent(tryAgainLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(gamePanelLayout.createSequentialGroup()
                        .addComponent(gameScoreLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(gamePanelLayout.createSequentialGroup()
                        .addComponent(gameBackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gameLabel)
                        .addGap(132, 132, 132)
                        .addComponent(gameSkipButton)
                        .addGap(24, 24, 24))))
            .addGroup(gamePanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(niceLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        gamePanelLayout.setVerticalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gamePanelLayout.createSequentialGroup()
                        .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gameLabel)
                            .addComponent(gameSkipButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                        .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(letter1Label)
                            .addComponent(letter2Label)
                            .addComponent(letter3Label)
                            .addComponent(letter4Label)
                            .addComponent(letter5Label)
                            .addComponent(letter6Label)
                            .addComponent(letter7Label)
                            .addComponent(letter8Label)
                            .addComponent(answerLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gamePanelLayout.createSequentialGroup()
                                .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(aButton)
                                    .addComponent(bButton)
                                    .addComponent(cButton)
                                    .addComponent(dButton)
                                    .addComponent(eButton)
                                    .addComponent(fButton)
                                    .addComponent(gButton)
                                    .addComponent(hButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton)
                                    .addComponent(kButton)
                                    .addComponent(lButton)
                                    .addComponent(mButton)
                                    .addComponent(nButton)
                                    .addComponent(oButton)
                                    .addComponent(pButton)
                                    .addComponent(qButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rButton)
                                    .addComponent(sButton)
                                    .addComponent(tButton)
                                    .addComponent(uButton)
                                    .addComponent(vButton)
                                    .addComponent(wButton)
                                    .addComponent(xButton)
                                    .addComponent(yButton)
                                    .addComponent(zButton)))
                            .addComponent(iButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(gamePanelLayout.createSequentialGroup()
                        .addComponent(gameBackButton)
                        .addGap(27, 27, 27)
                        .addComponent(gameScoreLabel)
                        .addGap(18, 18, 18)
                        .addComponent(niceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tryAgainLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        mainPanel.add(gamePanel, "gamePanel");

        scorePanel.setPreferredSize(new java.awt.Dimension(600, 400));

        scoreLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        scoreLabel.setText("Highscores");

        scoreBackButton.setText("Back");
        scoreBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scoreBackButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout scorePanelLayout = new javax.swing.GroupLayout(scorePanel);
        scorePanel.setLayout(scorePanelLayout);
        scorePanelLayout.setHorizontalGroup(
            scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scorePanelLayout.createSequentialGroup()
                .addGroup(scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(scorePanelLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(scoreLabel))
                    .addGroup(scorePanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(scoreBackButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        scorePanelLayout.setVerticalGroup(
            scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scorePanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(scoreLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scoreBackButton)
                .addGap(33, 33, 33))
        );

        mainPanel.add(scorePanel, "scorePanel");

        creditsPanel.setPreferredSize(new java.awt.Dimension(600, 400));

        creditsLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        creditsLabel.setText("Credits");

        creditsBackButton.setText("Back");
        creditsBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creditsBackButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout creditsPanelLayout = new javax.swing.GroupLayout(creditsPanel);
        creditsPanel.setLayout(creditsPanelLayout);
        creditsPanelLayout.setHorizontalGroup(
            creditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditsPanelLayout.createSequentialGroup()
                .addGroup(creditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(creditsPanelLayout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(creditsLabel))
                    .addGroup(creditsPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(creditsBackButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        creditsPanelLayout.setVerticalGroup(
            creditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditsPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(creditsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(creditsBackButton)
                .addGap(32, 32, 32))
        );

        mainPanel.add(creditsPanel, "creditsPanel");

        gameOverPanel.setPreferredSize(new java.awt.Dimension(600, 400));

        gameOverLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        gameOverLabel.setText("Game Over!");

        gameOverEndButton.setText("End");
        gameOverEndButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gameOverEndButtonMousePressed(evt);
            }
        });

        finalScoreLabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        finalScoreLabel.setText("Score: 100");

        javax.swing.GroupLayout gameOverPanelLayout = new javax.swing.GroupLayout(gameOverPanel);
        gameOverPanel.setLayout(gameOverPanelLayout);
        gameOverPanelLayout.setHorizontalGroup(
            gameOverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameOverPanelLayout.createSequentialGroup()
                .addGroup(gameOverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameOverPanelLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(gameOverLabel))
                    .addGroup(gameOverPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(gameOverEndButton)))
                .addContainerGap(196, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameOverPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(finalScoreLabel)
                .addGap(245, 245, 245))
        );
        gameOverPanelLayout.setVerticalGroup(
            gameOverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameOverPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(gameOverLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(finalScoreLabel)
                .addGap(122, 122, 122)
                .addComponent(gameOverEndButton)
                .addGap(34, 34, 34))
        );

        mainPanel.add(gameOverPanel, "gameOverPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gameButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameButtonMousePressed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(gamePanel);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        score = 100;
        gameScoreLabel.setText("Score: " + score);
        
        word = wordSelect();
        wordLength = word.length();
        lettersRemaining = wordLength;
        
        letter1Label.setText("___");
        letter2Label.setText("___");
        letter3Label.setText("___");
        letter4Label.setText("___");
        letter5Label.setText("___");
        letter6Label.setText("___");
        letter7Label.setText("___");
        letter8Label.setText("___");
        letter6Label.setVisible(true);
        letter7Label.setVisible(true);
        letter8Label.setVisible(true);
        if (wordLength == 5) {
            letter6Label.setVisible(false);
            letter7Label.setVisible(false);
            letter8Label.setVisible(false);
        }
        
        niceLabel.setVisible(false);
        tryAgainLabel.setVisible(false);
        
        aButton.setEnabled(true);
        bButton.setEnabled(true);
        cButton.setEnabled(true);
        dButton.setEnabled(true);
        eButton.setEnabled(true);
        fButton.setEnabled(true);
        gButton.setEnabled(true);
        hButton.setEnabled(true);
        iButton.setEnabled(true);
        jButton.setEnabled(true);
        kButton.setEnabled(true);
        lButton.setEnabled(true);
        mButton.setEnabled(true);
        nButton.setEnabled(true);
        oButton.setEnabled(true);
        pButton.setEnabled(true);
        qButton.setEnabled(true);
        rButton.setEnabled(true);
        sButton.setEnabled(true);
        tButton.setEnabled(true);
        uButton.setEnabled(true);
        vButton.setEnabled(true);
        wButton.setEnabled(true);
        xButton.setEnabled(true);
        yButton.setEnabled(true);
        zButton.setEnabled(true);
    }//GEN-LAST:event_gameButtonMousePressed

    private void scoreButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scoreButtonMousePressed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(scorePanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_scoreButtonMousePressed

    private void creditsButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditsButtonMousePressed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(creditsPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_creditsButtonMousePressed

    private void gameBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameBackButtonMouseClicked
        // TODO add your handling code here:
        returnMenu();
    }//GEN-LAST:event_gameBackButtonMouseClicked

    private void scoreBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scoreBackButtonMouseClicked
        // TODO add your handling code here:
        returnMenu();
    }//GEN-LAST:event_scoreBackButtonMouseClicked

    private void creditsBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditsBackButtonMouseClicked
        // TODO add your handling code here:
        returnMenu();
    }//GEN-LAST:event_creditsBackButtonMouseClicked

    private void gameOverEndButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameOverEndButtonMousePressed
        // TODO add your handling code here:
        returnMenu();
    }//GEN-LAST:event_gameOverEndButtonMousePressed

    private void gameSkipButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameSkipButtonMouseClicked
        // TODO add your handling code here:
        score = 0;
        gameOverDisplay();
    }//GEN-LAST:event_gameSkipButtonMouseClicked

    private void aButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aButtonMouseClicked
        // TODO add your handling code here:
        letterSelected(aButton);
    }//GEN-LAST:event_aButtonMouseClicked

    private void bButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bButtonMouseClicked
        // TODO add your handling code here:
        letterSelected(bButton);
    }//GEN-LAST:event_bButtonMouseClicked

    private void cButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cButtonMouseClicked
        // TODO add your handling code here:
        letterSelected(cButton);
    }//GEN-LAST:event_cButtonMouseClicked

    private void dButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dButtonMouseClicked
        // TODO add your handling code here:
        letterSelected(dButton);
    }//GEN-LAST:event_dButtonMouseClicked

    private void eButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eButtonMouseClicked
        // TODO add your handling code here:
        letterSelected(eButton);
    }//GEN-LAST:event_eButtonMouseClicked

    private void fButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fButtonMouseClicked
        // TODO add your handling code here:
        letterSelected(fButton);
    }//GEN-LAST:event_fButtonMouseClicked

    private void gButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gButtonMouseClicked
        // TODO add your handling code here:
        letterSelected(gButton);
    }//GEN-LAST:event_gButtonMouseClicked

    private void hButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hButtonMouseClicked
        // TODO add your handling code here:
        letterSelected(hButton);
    }//GEN-LAST:event_hButtonMouseClicked

    private void iButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iButtonMouseClicked
        // TODO add your handling code here:
        letterSelected(iButton);
    }//GEN-LAST:event_iButtonMouseClicked

    private void jButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMouseClicked
        // TODO add your handling code here:
        letterSelected(jButton);
    }//GEN-LAST:event_jButtonMouseClicked

    private void kButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButtonMouseClicked
        // TODO add your handling code here:
        letterSelected(kButton);
    }//GEN-LAST:event_kButtonMouseClicked

    private void lButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lButtonMouseClicked
        // TODO add your handling code here:
        letterSelected(lButton);
    }//GEN-LAST:event_lButtonMouseClicked

    private void mButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mButtonMouseClicked
        // TODO add your handling code here:
        letterSelected(mButton);
    }//GEN-LAST:event_mButtonMouseClicked

    private void nButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nButtonMouseClicked
        // TODO add your handling code here:
        letterSelected(nButton);
    }//GEN-LAST:event_nButtonMouseClicked

    private void oButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oButtonMouseClicked
        // TODO add your handling code here:
        letterSelected(oButton);
    }//GEN-LAST:event_oButtonMouseClicked

    private void pButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pButtonMouseClicked
        // TODO add your handling code here:
        letterSelected(pButton);
    }//GEN-LAST:event_pButtonMouseClicked

    private void qButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qButtonMouseClicked
        // TODO add your handling code here:
        letterSelected(qButton);
    }//GEN-LAST:event_qButtonMouseClicked

    private void rButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rButtonMouseClicked
        // TODO add your handling code here:
        letterSelected(rButton);
    }//GEN-LAST:event_rButtonMouseClicked

    private void sButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sButtonMouseClicked
        // TODO add your handling code here:
        letterSelected(sButton);
    }//GEN-LAST:event_sButtonMouseClicked

    private void tButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tButtonMouseClicked
        // TODO add your handling code here:
        letterSelected(tButton);
    }//GEN-LAST:event_tButtonMouseClicked

    private void uButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uButtonMouseClicked
        // TODO add your handling code here:
        letterSelected(uButton);
    }//GEN-LAST:event_uButtonMouseClicked

    private void vButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vButtonMouseClicked
        // TODO add your handling code here:
        letterSelected(vButton);
    }//GEN-LAST:event_vButtonMouseClicked

    private void wButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wButtonMouseClicked
        // TODO add your handling code here:
        letterSelected(wButton);
    }//GEN-LAST:event_wButtonMouseClicked

    private void xButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xButtonMouseClicked
        // TODO add your handling code here:
        letterSelected(xButton);
    }//GEN-LAST:event_xButtonMouseClicked

    private void yButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yButtonMouseClicked
        // TODO add your handling code here:
        letterSelected(yButton);
    }//GEN-LAST:event_yButtonMouseClicked

    private void zButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zButtonMouseClicked
        // TODO add your handling code here:
        letterSelected(zButton);
    }//GEN-LAST:event_zButtonMouseClicked

    private void letterSelected(javax.swing.JButton button) {
        boolean letterFound = false;
        if (button.isEnabled())
            for (int i = 0; i < word.length(); i++) {
                String letter = String.valueOf(word.charAt(i));
                if (letter.equalsIgnoreCase(button.getText())) {
                    displayLetter(i, letter.toUpperCase());
                    lettersRemaining--;
                    letterFound = true;
                }
            }
        if (!letterFound) {
            score -= 10;
            gameScoreLabel.setText("Score: " + score);
            tryAgainLabel.setVisible(true);
            niceLabel.setVisible(false);
        }
        if (score == 40)
            gameOverDisplay();
        if (lettersRemaining == 0)
            gameOverDisplay();
        button.setEnabled(false);
    }
    
    private void displayLetter(int index, String letter) {
        if (index == 0)
            letter1Label.setText(" " + letter + " ");
        if (index == 1)
            letter2Label.setText(" " + letter + " ");
        if (index == 2)
            letter3Label.setText(" " + letter + " ");
        if (index == 3)
            letter4Label.setText(" " + letter + " ");
        if (index == 4)
            letter5Label.setText(" " + letter + " ");
        if (index == 5)
            letter6Label.setText(" " + letter + " ");
        if (index == 6)
            letter7Label.setText(" " + letter + " ");
        if (index == 7)
            letter8Label.setText(" " + letter + " ");
        niceLabel.setVisible(true);
        tryAgainLabel.setVisible(false);
    }
    
    private void gameOverDisplay() {
        mainPanel.removeAll();
        mainPanel.add(gameOverPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        finalScoreLabel.setText("Score: " + score);
    }
    
    private void returnMenu() {
        mainPanel.removeAll();
        mainPanel.add(menuPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }
    
    private String wordSelect() {
        Random rand = new Random();
        String[] wordList = {"abstract", "cemetery", "nurse", "pharmacy", "climbing"};
        return wordList[rand.nextInt(5)];
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SemesterProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SemesterProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SemesterProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SemesterProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SemesterProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aButton;
    private javax.swing.JLabel answerLabel;
    private javax.swing.JButton bButton;
    private javax.swing.JButton cButton;
    private javax.swing.JButton creditsBackButton;
    private javax.swing.JButton creditsButton;
    private javax.swing.JLabel creditsLabel;
    private javax.swing.JPanel creditsPanel;
    private javax.swing.JButton dButton;
    private javax.swing.JButton eButton;
    private javax.swing.JButton fButton;
    private javax.swing.JLabel finalScoreLabel;
    private javax.swing.JButton gButton;
    private javax.swing.JButton gameBackButton;
    private javax.swing.JButton gameButton;
    private javax.swing.JLabel gameLabel;
    private javax.swing.JButton gameOverEndButton;
    private javax.swing.JLabel gameOverLabel;
    private javax.swing.JPanel gameOverPanel;
    private javax.swing.JPanel gamePanel;
    private javax.swing.JLabel gameScoreLabel;
    private javax.swing.JButton gameSkipButton;
    private javax.swing.JLabel groupLabel;
    private javax.swing.JButton hButton;
    private javax.swing.JButton iButton;
    private javax.swing.JButton jButton;
    private javax.swing.JButton kButton;
    private javax.swing.JButton lButton;
    private javax.swing.JLabel letter1Label;
    private javax.swing.JLabel letter2Label;
    private javax.swing.JLabel letter3Label;
    private javax.swing.JLabel letter4Label;
    private javax.swing.JLabel letter5Label;
    private javax.swing.JLabel letter6Label;
    private javax.swing.JLabel letter7Label;
    private javax.swing.JLabel letter8Label;
    private javax.swing.JButton mButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton nButton;
    private javax.swing.JLabel niceLabel;
    private javax.swing.JButton oButton;
    private javax.swing.JButton pButton;
    private javax.swing.JLabel projectLabel;
    private javax.swing.JButton qButton;
    private javax.swing.JButton rButton;
    private javax.swing.JButton sButton;
    private javax.swing.JButton scoreBackButton;
    private javax.swing.JButton scoreButton;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JPanel scorePanel;
    private javax.swing.JPanel startPanel;
    private javax.swing.JButton tButton;
    private javax.swing.JLabel tryAgainLabel;
    private javax.swing.JButton uButton;
    private javax.swing.JButton vButton;
    private javax.swing.JButton wButton;
    private javax.swing.JButton xButton;
    private javax.swing.JButton yButton;
    private javax.swing.JButton zButton;
    // End of variables declaration//GEN-END:variables
}
